version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - campaign-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # AWS Credentials (replace with your values or use .env file)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      
      # AgentCore Configuration
      - AGENTCORE_API_KEY=${AGENTCORE_API_KEY}
      - AGENTCORE_ENDPOINT=${AGENTCORE_ENDPOINT:-https://api.agentcore.aws.dev}
      
      # Application Settings
      - PORT=8000
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      # Persist agent outputs and downloads
      - ./public:/app/public
    restart: unless-stopped
    networks:
      - campaign-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  campaign-network:
    driver: bridge
